### PR TITLE
fixes #53 Fix schema validation for non mandatory fields

### LINKED ISSUE #53: Response schema validation
The response serialisation for the GET APIs seems to block the 'where', 'why' and 'meta' fields. Even if the audit data stored has these as objects, the response is always empty for these fields.

I am using the fustily-plugin, and if we bypass the response schema or use JSON.stringify the response includes the above fields.

### PR DESCRIPTION
**Pull request by vjaitly**
The where, why and meta fields had missing additional properties, hence getting dropped while serialisation

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Can you please add a test?

**Comment by vjaitly** [comment]
> Can you please add a test?

@simoneb haven't been able to setup the tests, in my dev environment. Keep getting the error 'role postgres does not exist'.  The env override that works for a normal run, does not seem to be working here.
Any pointers on how to properly setup the same.

**Comment by simoneb** [comment]
> > Can you please add a test?
> 
> @simoneb haven't been able to setup the tests, in my dev environment. Keep getting the error 'role postgres does not exist'. The env override that works for a normal run, does not seem to be working here.
> Any pointers on how to properly setup the same.

If you write the test inspiring from how the existing tests are written, even if you can't set up a local DB we can see if the test succeeds in the checks which are run as part of the PR CI. 

The CI configuration file might be useful to see how to set up your local db though https://github.com/nearform/trail/blob/master/.travis.yml

**Review by simoneb — APPROVED** [review]
LGTM

**Comment by simoneb** [comment]
@vjaitly are you happy with the implementation? If so, we can merge this.

**Comment by vjaitly** [comment]
All good. Thanks @simoneb

**Pull request merged**
