### PR TITLE
Fixes #60 Validate boolean parameter option

### LINKED ISSUE #60: [Documentation] ReadMe is not updated
The options in `trail-fastify-server` readme is not in sync with the implementation. The following options needs to be fixed:
```
   TRAIL_DISABLE_REST_API
   TRAIL_DISABLE_GRAPHQL
   --noRestAPI (Command Line)
   --noGraphql (Command Line)
```
The implemented options are
```
   TRAIL_USE_REST_API
   TRAIL_USE_GRAPHQL
   --useRESTAPI
   --useGraphQL
```
Also the boolean value do not take effect if `false` is passed in the parameter

### PR DESCRIPTION
**Pull request by vjaitly**
fixed config parameter of boolean type not working for `false` value

### CODE REVIEW

**Comment by vjaitly** [comment]
@simoneb Tried setting up a new environment using `npm install @nearform/trail-fastify-server`.
I don't see the merged files in that environment. Any idea how to take the latest version from master . Adding `@latest` did not work either. 
Is there a version bump required ?

**Comment by simoneb** [comment]
you'll need to use npm link to use an unreleased version of a package

**Review by simoneb — COMMENTED** [review]
Do you think we can keep the same semantics as before (negated conditions)? I'm concerned about the breaking change. Ok to fix the issue, but if possible I would preserve the previous CLI flags and env var names (assuming they were actually being used, despite with wrong behavior due to the bug)

**Comment by vjaitly** [comment]
> you'll need to use npm link to use an unreleased version of a package

An example would be very helpful

**Comment by vjaitly** [comment]
> Do you think we can keep the same semantics as before (negated conditions)? I'm concerned about the breaking change. Ok to fix the issue, but if possible I would preserve the previous CLI flags and env var names (assuming they were actually being used, despite with wrong behavior due to the bug)

@simoneb The negated conditions was only in the README file. The actual variables in the code are `TRAIL_USE_REST_API` and `TRAIL_USE_GRAPHQL`. So it would not have worked even if some one was to use the variable as per the README

**Comment by simoneb** [comment]
> > Do you think we can keep the same semantics as before (negated conditions)? I'm concerned about the breaking change. Ok to fix the issue, but if possible I would preserve the previous CLI flags and env var names (assuming they were actually being used, despite with wrong behavior due to the bug)
> 
> @simoneb The negated conditions was only in the README file. The actual variables in the code are `TRAIL_USE_REST_API` and `TRAIL_USE_GRAPHQL`. So it would not have worked even if some one was to use the variable as per the README

Oh that's perfect then, thanks.

**Comment by simoneb** [comment]
> > you'll need to use npm link to use an unreleased version of a package
> 
> An example would be very helpful

in the unreleased package (e.g. @nearform/trail-fastify-plugin) root dir:

`npm link`

in the root dir of the package where you want to use the unreleased package:

`npm link @nearform/trail-fastify-plugin`

Don't forget to npm unlink the package once you're done with it.

**Comment by vjaitly** [comment]
> > > you'll need to use npm link to use an unreleased version of a package
> > 
> > 
> > An example would be very helpful
> 
> in the unreleased package (e.g. @nearform/trail-fastify-plugin) root dir:
> 
> `npm link`
> 
> in the root dir of the package where you want to use the unreleased package:
> 
> `npm link @nearform/trail-fastify-plugin`
> 
> Don't forget to npm unlink the package once you're done with it.

Thanks, will give it a try. It would work only in my local environment then ?
When does this get a released status ?

**Comment by simoneb** [comment]
Yes it should work on your local environment. Since you're making quite a few changes I would like to wait and batch them together before making the next release.

**Comment by vjaitly** [comment]
ok.. That should work for now. Any other changes for this request ?

**Review by simoneb — APPROVED** [review]

**Comment by simoneb** [comment]
> Yes it should work on your local environment. Since you're making quite a few changes I would like to wait and batch them together before making the next release.

merged, thanks

**Pull request merged**
